### ISSUE TITLE
issue running python script

### ISSUE THREAD

**Issue by blackwiz4rd** [slozo/Network-listener#2]
Hi, I am having an issue running a python script when wifi connects to a particular network, the python script won't run.
I have all the settings setup correctly, in fact I have connection.txt showing output when connecting to a network.
I have a working python script named 'vodafone-wifi.py' in ~ folder
and I have edited .networkConnected like this:

`#!/bin/bash

if [[ "$1" == "NOT_CONNECTED" ]]; then
  echo $(date) connected to "$2" > ~/connection.txt
  python vodafone-wifi.py
else
  echo $(date) changed connection from "$1" to "$2" > ~/disconnection.txt
fi
`

What may cause the problem?

**Comment by slozo** [comment]
Hi,

Maybe try the full path to Python ( It might be missing from the PATH)  so probably it will be /usr/bin/python

Hope it helps!

Wysłane z iPhone'a

Dnia 01.03.2016 o godz. 18:10 Luca notifications@github.com napisał(a):

**Comment by blackwiz4rd** [comment]
Thanks for the quick answer, I will let you know if it works, you mean by adding
#!/usr/bin/python
at the start of .networkConnected right?
Because I have already specified the full path in my python script

**Comment by slozo** [comment]
No no, I mean to give full path to python inside .networkConnected script like:

`#!/bin/bash

if [[ "$1" == "NOT_CONNECTED" ]]; then
echo $(date) connected to "$2" > ~/connection.txt
/usr/bin/python vodafone-wifi.py
else
echo $(date) changed connection from "$1" to "$2" > ~/disconnection.txt
fi
`

script is run from the daemon and it might be, that there’s missing PATH to /usr/bin inside its environment.

You can also specify path to the vodafone-wifi.py (like ~/vodafone-wifi.py) script, since .networkConnected script might not be aware of the „working directory” - just guessing.

/Mateusz

**Comment by blackwiz4rd** [comment]
Great! Now it's working. I have to deal with some python exceptions that weren't raised before but yours is the solution for this problem.
Thanks a lot.

**Comment by slozo** [comment]
No problem Cheers!

/Mateusz
